version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dodoo
    ports:
      - "127.0.0.1:2222:22"
      - "8069:8069"
    volumes:
      - ~/code:/opt/odoo
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo

  db:
    image: "postgres:10.4"
    container_name: postgres
    hostname: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
